### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by teovoinea** [Floppy/ruby-version-badger#1]
Not much code to review, but not bad! Just some small nitpicky stuff:

- This [if else block](https://github.com/Floppy/ruby-version-badger/blob/master/src/handlers.rs#L32) could be replaced with a match statement
- Every time this [function ](https://github.com/Floppy/ruby-version-badger/blob/master/src/handlers.rs#L59) is called, the regex gets recompiled. Not a huge issue now but it's a pretty easy optimization

**Comment by Floppy** [comment]
Thanks!

**Comment by Floppy** [comment]
Ah, interestingly, the if/else; I had started with a match, but was getting complaints about not being able to use `String` objects, so I fell back to the if/else. I'll have another go now it's more stable.

**Comment by teovoinea** [comment]
Maybe this [resource](https://stackoverflow.com/questions/25383488/how-to-match-a-string-against-string-literals-in-rust) would help?

**Comment by Floppy** [comment]
Brilliant, that looks like the answer. I figured there must be something like `as_ref` but didn't find it before dealing with bigger issues and moving on. Thanks!
